sudo: required
services:
    - docker

before_install:
    - docker build -t evansroony/docker-react -f Dockerfile.dev .
    - travis_wait 30 mvn install

script:
    - docker run evansroony/docker-react npm run test -- --coverage